openapi: 3.0.0
info:
  title: Alerts App
  description: Alerts API.
  contact:
    email: radoslawtomczynski@gmail.com
  version: 1.0.0
servers:
- url: http://localhost:8000/v1
tags:
- name: user
  description: User endpoints
- name: oauth
  description: Ouath2 endpoints
- name: alerts
  description: Alerts endpoints
paths:
  /signup:
    post:
      tags:
      - user
      summary: Signs up User
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                      example: "users"
                    attributes:
                      type: object
                      properties:
                        email:
                          type: string
                          example: "valid@email.com"
                        password:
                          type: string
                          example: "password123"
      responses:
        '202':
          description: Accepted - even when users already exists.
          content:
            application/vnd.api+json:
              schema:
               type: object
               properties:
                 data:
                   type: integer
                   nullable: true
                   example: null
        '422':
          description: Unprocessable Entity
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        source:
                          type: string
              examples:
                emailMissing:
                  value: [
                    { code: "missing", source: "/data/attributes/email" }
                  ]
                emailBlank:
                  value: [
                    { code: "blank", source: "/data/attributes/email" }
                  ]
                emailFormatInvalid:
                  value: [
                    { code: "formatInvalid", source: "/data/attributes/email" }
                  ]
                passwordMissing:
                  value: [
                    { code: "missing", source: "/data/attributes/password" },
                  ]
                passwordBlank:
                  value: [
                    { code: "blank", source: "/data/attributes/password" },
                  ]
                passwordTooShort:
                  value: [
                    { code: "tooShort", source: "/data/attributes/password" },
                  ]
  /token:
    post:
      tags:
      - oauth
      summary: Gets access token in Oauth 2.0 standard
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  example: "password"
                username:
                  type: string
                  example: "email@email.com"
                password:
                  type: string
                  example: "password"
                refresh_token:
                  type: string
                  example: "refresh_token"
            examples:
              password:
                summary: Password authentication
                value: { grant_type: "password", username: "username123", password: "password123" }
              refresh_token:
                summary: Refresh token authentication
                value: { grant_type: "refresh_token", refresh_token: "8a7d6adagdadhah7s6d76ad76" }
      responses:
        200:
          description: OK - access granted.
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: "MTQ0NjOkZmQ5OTM5NDE9ZTZjNGZmZjI3"
                  token_type:
                    type: string
                    example: "bearer"
                  expires_in:
                    type: integer
                    example: 86_400
                  refresh_token:
                    type: string
                    example: "8a7d6adagdadhah7s6d76ad76"
        400:
          description: Bad Request
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  error:
                    type: "string"
              examples:
                invalid_grant:
                  description: The authorization code is invalid or expired.
                  value: { error: "invalid_grant" }
                invalid_request:
                  description: The request is missing a parameter so the server can’t proceed with the request.
                  value: { error: "invalid_request" }
                unsupported_grant_type:
                  description:  Requested grant type is not recognized by the authorization server.
                  value: { error: "unsupported_grant_type" }

  /me/alerts:
    get:
      tags:
      - alerts
      summary: Lists user's alerts.
      responses:
        '200':
          description: Accepted.
          content:
            application/vnd.api+json:
              schema:
               type: object
               properties:
                 data:
                   type: array
                   items:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          uuid:             
                            type: string
                            format: uuid
                            example: "1e9e35fb-224d-4075-9f64-fe037c7167a6"
                          market_uuid:      
                            type: string
                            format: uuid
                            example: "1e9e35fb-224d-4075-9f64-fe037c7167a6"
                          user_uuid:        
                            type: string
                            format: uuid
                            example: "1e9e35fb-224d-4075-9f64-fe037c7167a6"
                          activation_price: 
                            type: number
                            example: 1.23
                          trigger_price:    
                            type: number
                            example: 4.56
                          triggered_at:
                            type: string
                            format: date-time
                            example: "2017-07-21T17:32:28Z"
                          turned_off_at:
                            type: string
                            format: date-time
                            example: "2017-07-21T17:32:28Z"
                          triggered?:
                            type: boolean
                            example: true
                          turned_off?:
                            type: boolean
                            example: true
        '401':
          description: Unauthorized.
    post:
      tags:
      - alerts
      summary: Creates a new Alert
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                      example: "alerts"
                    attributes:
                      type: object
                      properties:
                        market_uuid:
                          type: string
                          example: "1e9e35fb-224d-4075-9f64-fe037c7167a6"
                        activation_price:
                          type: number
                          example: 1.23
                        trigger_price:
                          type: number
                          example: 4.56
      responses:
        '202':
          description: Accepted.
          content:
            application/vnd.api+json:
              schema:
               type: object
               properties:
                 data:
                   type: integer
                   nullable: true
                   example: null
        '401':
          description: Unauthorized.
        '422':
          description: Unprocessable Entity
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        source:
                          type: string
              examples:
                marketUuidMissing:
                  value: [
                    { code: "missing", source: "/data/attributes/market_uuid" }
                  ]
                marketUuidBlank:
                  value: [
                    { code: "blank", source: "/data/attributes/market_uuid" }
                  ]
                activationPriceMissing:
                  value: [
                    { code: "missing", source: "/data/attributes/activation_price" }
                  ]
                activationPriceLessOrEqualZero:
                  value: [
                    { code: "less_or_equal_zero", source: "/data/attributes/activation_price" }
                  ]
                triggerPriceMissing:
                  value: [
                    { code: "missing", source: "/data/attributes/trigger_price" }
                  ]
                triggerPriceLessOrEqualZero:
                  value: [
                    { code: "less_or_equal_zero", source: "/data/attributes/trigger_price" }
                  ]
  /me/alerts/{alert_uuid}/turn_off:
    post:
      tags:
      - alerts
      summary: Turns off the alert.
      parameters:
        - in: path
          name: alert_uuid
          schema:
            type: string
          required: true
          description: UUID of the alert.
      responses:
        '202':
          description: Accepted.
          content:
            application/vnd.api+json:
              schema:
               type: object
               properties:
                 data:
                   type: integer
                   nullable: true
                   example: null
        '401':
          description: Unauthorized.
  /me/alerts/{alert_uuid}:
    delete:
      tags:
      - alerts
      summary: Delets the alert.
      parameters:
        - in: path
          name: alert_uuid
          schema:
            type: string
          required: true
          description: UUID of the alert.
      responses:
        '202':
          description: Accepted.
          content:
            application/vnd.api+json:
              schema:
               type: object
               properties:
                 data:
                   type: integer
                   nullable: true
                   example: null
        '401':
          description: Unauthorized.\
