openapi: 3.0.0
info:
  title: Alerts App
  description: Alerts API.
  contact:
    email: radoslawtomczynski@gmail.com
  version: 1.0.0
servers:
- url: http://localhost:8000/v1
tags:
- name: user
  description: Operations about user
paths:
  /signup:
    post:
      tags:
      - user
      summary: Signs up user
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    type:
                      type: string
                      example: "users"
                    attributes:
                      type: object
                      properties:
                        email:
                          type: string
                          example: "valid@email.com"
                        password:
                          type: string
                          example: "password123"
      responses:
        '202':
          description: Accepted - even when users already exists.
          content:
            application/vnd.api+json:
              schema:
               type: object
               properties:
                 data:
                   type: integer
                   nullable: true
                   example: null
        '422':
          description: Unprocessable Entity
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        source:
                          type: string
              examples:
                emailMissing:
                  value: [
                    { code: "missing", source: "/data/attributes/email" }
                  ]
                emailBlank:
                  value: [
                    { code: "blank", source: "/data/attributes/email" }
                  ]
                emailFormatInvalid:
                  value: [
                    { code: "formatInvalid", source: "/data/attributes/email" }
                  ]
                passwordMissing:
                  value: [
                    { code: "missing", source: "/data/attributes/password" },
                  ]
                passwordBlank:
                  value: [
                    { code: "blank", source: "/data/attributes/password" },
                  ]
                passwordTooShort:
                  value: [
                    { code: "tooShort", source: "/data/attributes/password" },
                  ]
  /token:
    post:
      tags:
      - oauth
      summary: Gets access token in Oauth 2.0 standard
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  example: "password"
                username:
                  type: string
                  example: "email@email.com"
                password:
                  type: string
                  example: "password"
                refresh_token:
                  type: string
                  example: "refresh_token"
            examples:
              password:
                summary: Password authentication
                value: { grant_type: "password", username: "username123", password: "password123" }
              refresh_token:
                summary: Refresh token authentication
                value: { grant_type: "refresh_token", refresh_token: "8a7d6adagdadhah7s6d76ad76" }
      responses:
        200:
          description: OK - access granted.
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: "MTQ0NjOkZmQ5OTM5NDE9ZTZjNGZmZjI3"
                  token_type:
                    type: string
                    example: "bearer"
                  expires_in:
                    type: integer
                    example: 86_400
                  refresh_token:
                    type: string
                    example: "8a7d6adagdadhah7s6d76ad76"
        400:
          description: Bad Request
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  error:
                    type: "string"
              examples:
                invalid_grant:
                  description: The authorization code is invalid or expired.
                  value: { error: "invalid_grant" }
                invalid_request:
                  description: The request is missing a parameter so the server can’t proceed with the request.
                  value: { error: "invalid_request" }
                unsupported_grant_type:
                  description:  Requested grant type is not recognized by the authorization server.
                  value: { error: "unsupported_grant_type" }
